spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.224.129:3306/study_spring_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: could-provider-payment-service
  cloud:
    zookeeper:
      connect-string: 192.168.224.129:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8001
