spring:
  application:
    name: could-config-service
  cloud:
    consul:
      host: 192.168.224.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    config:
      label: master #指定读取分支
      server:
        git:
          uri: https://github.com/LQliuqiang/springcould-config.git #仓库名称
          search-paths:
            - springcloud-config #搜索上面指定仓库下的目录
  rabbitmq:
    host: 192.168.224.129
    port: 5672
    username: guest
    password: guest


server:
  port: 3344


#rabbitmq相关配置，暴露bus刷新配制的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

