spring:
  application:
    name: could-provider-consul-payment-service
  cloud:
    consul:
      host: 192.168.224.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}


server:
  port: 8002
